
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwoqkzwgjomhrzejdaiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3b3Frendnam9taHJ6ZWpkYWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjA4ODUyMjksImV4cCI6MjAzNjQ2MTIyOX0.TEwX9VK1Gt9Jv9VOTGvfuiMP6dh5yvdPllYqg6C7H3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
